### PR TITLE
Fixing the non-use of default values in OptionGroups

### PR DESCRIPTION
**Pull request by bnbowman**

### CODE REVIEW

**Comment by weisslj** [comment]
Thank you very much for your patch, and apologies for responding so late.

**Comment by myint** [comment]
Doesn't this end up duplicating the group option? It seems to me that, in `--help`, it will end up being listed in both the normal `Options:` and in the group options.

**Comment by weisslj** [comment]
@myint: You are right, thanks! This should be fixed in 1f6c809.

**Comment by myint** [comment]
@weisslj, just out of curiosity, why are there two repositories with essentially the same content?

https://github.com/weisslj/cpp-argparse
https://github.com/weisslj/cpp-optparse

**Comment by weisslj** [comment]
The cpp-argparse repository was meant as a rewrite/successor of cpp-optparse, to keep up with the new [argparse Python library](https://docs.python.org/3/library/argparse.html).

**Pull request merged**
